name: test

on: [push, pull_request]

jobs:


  run-syntax-tests:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $PWD
          git config --local --get remote.origin.url || true
        shell: bash
      - uses: actions/checkout@v2
      - run: |
          echo $PWD
          git config --local --get remote.origin.url
        shell: bash
      - uses: actions/checkout@v2
        with:
          repository: randy3k/radian
      - run: |
          echo $PWD
          git config --local --get remote.origin.url
        shell: bash
